### ISSUE TITLE
Tab icon after touching the crown not shown

### ISSUE THREAD

**Issue by usersaurus** [idolize/logitech-craft-vscode#11]
Hi! Before all, thank you so much for doing this :D Great job with it.

After installing it, I'm running into two issues with the plugin:

- The change tab icon is not getting shown after touching the crown. I think it should be shown after seen these images in the plugin folder.
- Crown movement is "smooth" instead of having the "tick tick" feedback (don't know how to explain it lol) that you can feel when using the crown in google chrome while changing tabs.

**Comment by idolize** [comment]
@usersaurus Thanks for the feedback!

I'm not sure how to force the crown into the "ratchet" mode, but I've noticed that as well (I think it uses whatever mode you were last using, so in your case it's probably in smooth mode from volume control?). I may have to reach out to Logitech about this because the documentation is pretty slim on this topic.

The tab icon not being shown is actually by design, as I originally intended to hard code this, but later decided to make it customizable to *any* available VS Code action (thus making it difficult to ensure an appropriate icon is shown for each action).

Feel free to continue contributing feedback or even code changes!
